import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { getServerSession } from 'next-auth'
import Link from 'next/link'
import Logout from './logout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='flex flex-row gap-5 mx-2 max-w-md mt-5'>
          {!!session && <Logout/> }
          {!session && <Link href="/login">Sign In</Link> }
          {!session && <Link href="/register">Sign Up</Link> }
        </nav>
        {children}</body>
    </html>
  )
}
